### ISSUE TITLE
Get API key

### ISSUE THREAD

**Issue by vthnguyen70** [Food-Oasis/GobiRepo#20]

**Comment by AnthonyDavis2** [comment]
I've researched the information for the Google Maps API. 
Received the key to access the API and created a txt file to store the value.
The txt file should be an xml file but github doesnt allow those to be attached. 
*Check slack for the last five digits of the key. 

[map_api.txt](https://github.com/Food-Oasis/GobiRepo/files/3658859/map_api.txt)
